version: 1.0.{build}
build:
  verbosity: minimal

configuration: Release
#image: Visual Studio 2017
#platform: x64

environment:
  global:
    QT_32: "C:\\Qt\\5.10.1\\msvc2015"
    QT_64: "C:\\Qt\\5.10.1\\msvc2017_64"
    GENERATOR_32: "Visual Studio 15 2017"
    GENERATOR_64: "Visual Studio 15 2017 Win64"
    TWINE_USERNAME: mgb
    TWINE_PASSWORD:
      secure: 0nIEPxdiNLL2Hc+LQXJfCQ==
    
  matrix:
    # Python 3.6
    - PYTHON: "C:\\Python36-x64"
      QT: %QT_64%
     GENERATOR: "%GENERATOR_64%"
      
    - PYTHON: "C:\\Python36"
      QT: "%QT_32%"
      GENERATOR: "%GENERATOR_32%"
      
    # Python 3.5
    - PYTHON: "C:\\Python35-x64"
      QT: %QT_64%
     GENERATOR: "%GENERATOR_64%"
      
    - PYTHON: "C:\\Python35"
      QT: "%QT_32%"
      GENERATOR: "%GENERATOR_32%"      
      
    # Python 3.4
    - PYTHON: "C:\\Python34-x64"
      QT: %QT_64%
     GENERATOR: "%GENERATOR_64%"
      
    - PYTHON: "C:\\Python34"
      QT: "%QT_32%"
      GENERATOR: "%GENERATOR_32%"          

install:  
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "SET CMAKE_PREFIX_PATH=%QT%"
  - "python --version"
  - "pip install scikit-build"
  - "pip install numpy"
  - "pip install twine"
  
build_script:
  - python setup.py bdist_wheel -G "%GENERATOR%" 
 
artifacts:
  - path: "dist/*.whl"
     
deploy_script:
  - twine upload dist/*
