version: 1.0.{build}
build:
  verbosity: minimal

image: Visual Studio 2017
configuration: Release
platform: x64

environment:
  global:
    QT_32: "C:\\Qt\\5.10.1\\msvc2015"
    QT_64: "C:\\Qt\\5.10.1\\msvc2017_64"
    TWINE_USERNAME: mgb
    TWINE_PASSWORD:
      secure: 0nIEPxdiNLL2Hc+LQXJfCQ==
    
  matrix:
    #- PYTHON: "C:\\Python36-x64"
    #  QT: %QT_64%
    #  GENERATOR 
      
    - PYTHON: "C:\\Python36"
      QT: "%QT_32%"
      GENERATOR: "Visual Studio 15 2017"
      

install:  
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "SET CMAKE_PREFIX_PATH=%QT%"
  - "python --version"
  - "pip install scikit-build"
  - "pip install numpy"
  
build_script:
  #- python setup.py bdist_wheel -G "Visual Studio 15 2017 Win64" 
  - python setup.py bdist_wheel -G "%GENERATOR%" 
 
artifacts:
  - path: dist
    name: "qui"
 
deploy: no
#deploy_script:
#  - twine upload dist/*
